apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kkxuizi3v-python
  janus-idp.io/tekton: kkxuizi3v-python
  backstage.io/kubernetes-id: kkxuizi3v-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kkxuizi3v-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
